steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/music-recommender:$COMMIT_SHA', '.']

# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/music-recommender:$COMMIT_SHA']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'music-recommender'
  - '--image'
  - 'gcr.io/$PROJECT_ID/music-recommender:$COMMIT_SHA'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'

# Deploy pipeline to Vertex AI
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
    pip install kfp google-cloud-aiplatform
    python deployment/deploy_pipeline.py --platform vertex --project_id $PROJECT_ID --region ${_REGION} --output_file pipeline.yaml

images:
- 'gcr.io/$PROJECT_ID/music-recommender:$COMMIT_SHA'

substitutions:
  _REGION: us-central1  # default region, can be overridden