name: Model Deployment
description: Deploys the trained model
inputs:
  - {name: model, type: Model}
outputs:
  - {name: model_info, type: JsonObject}
implementation:
  container:
    image: gcr.io/your-project-id/lastfm-music-recommender:latest
    command:
      - python
      - /app/src/serving/model_serving.py
      - --model
      - {inputPath: model}
      - --model_info
      - {outputPath: model_info}
